implement right frozen
Comcast/react-data-grid pull request #3671
Opened 2024-12-16 11:00 UTC by robert-luoqing

I'm not override frozen to left | right | null, I just add rightFrozen property. It will not break original version.

2024-12-17 03:53 UTC, eshwaruppala commented
this is a necessary feature

2025-06-30 02:24 UTC, iamrakhmatov commented
@amanmahajan7 any news on this?

2025-07-23 17:21 UTC, ksparakis commented
Whats needed to get this across the finish line? willing to put resources on it

2025-07-25 12:20 UTC, shubh-philips commented
Any update on this feature merging?

2025-07-30 02:14 UTC, amanmahajan7 requested changes

2025-07-30 02:14 UTC, amanmahajan7 commented on src/types.ts
> +  readonly rightFrozen?: Maybe<boolean>;
I would rather not add a new prop that can cause conflicts. What happens when both `rightFrozen` and `frozen` props are set? We can instead change `frozen` to `boolean | 'left' | 'right'`.

2025-07-30 02:14 UTC, amanmahajan7 commented on src/hooks/useCalculatedColumns.ts
> +  const { columns, colSpanColumns, lastFrozenColumnIndex, rightFrozenColumnCount, headerRowsCount } = useMemo((): {
All the new functionality needs extensive tests

2025-09-23 14:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Comcast/react-data-grid?pullRequest=3671) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Comcast/react-data-grid?pullRequest=3671) before we can accept your contribution.<br/><hr/>**robert** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Comcast/react-data-grid?pullRequest=3671) it.</sub>

2026-04-17 17:15 UTC, PaloSP commented
Hi @amanmahajan7 

This PR has been stuck since July 2025. Right-side column pinning is a feature I need — happy to take it over with a fresh PR.

Before I invest time:

1. Still want `frozen: boolean | 'left' | 'right'` instead of a new `rightFrozen` prop?
2. Tests: unit + playwright e2e — any patterns you want beyond what's in the repo?
3. Review bandwidth — is this on your radar or effectively deprioritized?

If there's genuine interest, I'll open a PR within ~2 weeks. If not, please say so — I'll plan accordingly.

Thanks.

2026-04-21 14:58 UTC, amanmahajan7 commented
We will be happy to review the PR 

> Still want frozen: boolean | 'left' | 'right' instead of a new rightFrozen prop?

Yes. @nstepien wdyt?

> Tests: unit + playwright e2e — any patterns you want beyond what's in the repo?

We use vitest browser tests. Here is an example of testing frozen columns
https://github.com/Comcast/react-data-grid/blob/main/test/browser/column/frozen.test.ts

> Review bandwidth — is this on your radar or effectively deprioritized?

We can prioritize the review 

Few important notes
- This will affect virtualization logic so we should add more tests (https://github.com/Comcast/react-data-grid/blob/main/test/browser/virtualization.test.ts)
- We want to prevent the shadow logic (https://github.com/Comcast/react-data-grid/blob/main/src/style/core.ts#L96)
- Ensure RTL mode works as expected

2026-04-21 23:18 UTC, nstepien commented
> > Still want frozen: boolean | 'left' | 'right' instead of a new rightFrozen prop?
> 
> Yes. @nstepien wdyt?

I'd go with `frozen: boolean | 'start' | 'end'` so it's compatible with `direction="rtl"`

2026-04-24 17:55 UTC, PaloSP commented
Hi @robert-luoqing — I've opened #4034 as a fresh attempt at this feature, using the `frozen: boolean | 'start' | 'end'` API agreed with @amanmahajan7 and @nstepien. Full credit to your original work here, which informed the approach.

Feel free to close this PR if you'd like, or keep it open for reference — either way, thanks for getting the ball rolling on right-edge pinning.

2026-06-09 14:26 UTC, amanmahajan7 commented
Replaced by https://github.com/Comcast/react-data-grid/pull/4034

2026-06-09 14:26 UTC, closed without merging